variables:
  GIT_SUBMODULE_STRATEGY: recursive
cache:
  key: ${CI_JOB_NAME}

stages:
  - build

Build Linux:
  stage: build
  image: ssmethurst/ubuntudev-18_04:latest
  tags: 
    - docker 
  before_script:
    # update the build number 
    - echo -e "#define CI_PIPELINE_IID $CI_PIPELINE_IID\n" >CIBuildSettings.h 
    - "cat CIBuildSettings.h"
    # debug info 
    - "gcc -v" 
    - "ls" 
    # Clean the project 
    make clean  
  script:
    make all 
  artifacts:
    paths:
      serialMonitor 